# SPRING CORE
spring:
  application:
    name: Sample spring boot with kotlin
  output:
    ansi:
      enabled: detect
  datasource:
    url: jdbc:mysql://localhost:3306/zipcode?useSSL=false
    username: demo_user
    password: demo_pass
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      default-read-only: true
      validation-query: select 1
      validation-query-timeout: 3
      time-between-eviction-runs-millis: 3600000
      test-on-borrow: true
      test-while-idle: true
      test-on-connect: true
      remove-abandoned: true
      remove-abandoned-timeout: 60
      log-abandoned: true
      max-active: 2
      initial-size: 2
      max-idle: 4
      min-idle: 0
  jpa:
    open-in-view: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        generate_statistics: false
  jackson:
    serialization:
      indent-output: true
      write-dates-as-timestamps: false
      write-durations-as-timestamps: true

# Embedded server configuration
server:
  port: 8080
  servlet:
    context-path: /

logging:
  file: sample.log
  level:
    root: info
    org.springframework: info
    org.hibernate: info
    org.hibernate.SQL: debug
    com.example.demo: debug
    com.lasta.api: debug
